### ISSUE TITLE
About slimmable GCN

### ISSUE THREAD

**Issue by bhli168** [ycjing/AmalgamateGNN.PyTorch#2]
Hi
I am very interested with the slimmable GCN proposed in this paper in dealing with the heterogeneous nodes with different feature dimensions, but not sure which part of codes play that role. Could you please give me a hint? Thank you so much.

**Comment by ycjing** [comment]
Hi @bhli168 

Thank you for your interests in our work! And really sorry for the late response due to a recent paper submission deadline. For the slimmable graph convolutional operation, the current repo does not include this part, since the used example dataset in this repo is the PPI dataset. The implementation of slimmable graph convolution is straightforward, simply switching the weight channels for different inputs: `weight = self.weight[:, :in_channels]`. If anything else is not clear, please feel free to send me an email and I am more than happy to provide you with the sample code. 

Thank you for your interests again!

Best,
Yongcheng

**Comment by bhli168** [comment]
Hi
I have figured it out using the method which is the same with that you mentioned. I appreciate your reply, anyway.
